### ISSUE TITLE
Material Views are not listening to Background updates

### ISSUE THREAD

**Issue by ChasakisD** [ChasakisD/Xamarin.Forms.BackgroundKit#19]
MaterialBackgroundManager is not listening to background changes, so when you set Material Views' background to another Background instance, it has no effect

**Comment by toverux** [comment]
@ChasakisD I'm not able to change a background instance after it's been set.
Originally I tried via a Style with a trigger (to reduce Elevation to 0 when IsEnabled is false), but ultimately, even `MyMaterialView.Background = new Background { ... }` didn't worked better the moment it is called after the page initialization.
This is on Android, didn't tried iOS yet.

**Comment by ChasakisD** [comment]
@toverux Could you please fill a new issue with a reproduction code? I am working on production with this and is working fine
