### ISSUE TITLE
Issues with namespace

### ISSUE THREAD

**Issue by dalton5** [ChasakisD/Xamarin.Forms.BackgroundKit#21]
Hi

I have added the nugget and did the instanciation is the ios and android classes.

I use the  xmlns:background="http://xamarin.com/schemas/2014/forms/background"

When I add the background code I have the issue that: 
Error		Position 47:14. Type background:Background not found in xmlns http://xamarin.com/schemas/2014/forms/background	

My code is this:

Can you help please?

   </CarouselView.ItemTemplate>
          < background:BackgroundEffect.Background >
            <background:Background
                CornerRadius="5"
                Elevation="4"
                IsRippleEnabled="True"
                RippleColor="White"
                Color="Red" />
          </background:BackgroundEffect.Background>

**Comment by ChasakisD** [comment]
What IDE are you using?

For now, provide the full namespace with the assembly name inside the xmlns. One for XamarinBackgroundKit.Controls namespaces and one for XamarinBackgroundKit.Effects.

**Comment by dalton5** [comment]
I use VS 2019.

I am not sure to understand what you mean by provide the full namespace with the assembly name inside the xmlns

Would you have an example pleasE?

**Comment by ChasakisD** [comment]
Its kind of weird why you are getting a compile error. I actually use it in different solutions. Anyway, i will try to reproduce it. You can define the xmlns by the following:
```xml
xmlns:controls="clr-namespace:XamarinBackgroundKit.Controls;assembly=XamarinBackgroundKit"
xmlns:effects="clr-namespace:XamarinBackgroundKit.Effects;assembly=XamarinBackgroundKit"
```

**Comment by dalton5** [comment]
It works. Thanks

**Comment by ChasakisD** [comment]
@dalton5 Pushed version 1.1.0 to nuget. It will be listed soon. Please check if this version resolves the issue! :)

**Comment by pkoelbl** [comment]
I had to use the name spaces as above because i was getting an error on GradientStop
