### ISSUE TITLE
Getting a java.lang.NoSuchMethodError. 

### ISSUE THREAD

**Issue by uksreejith** [ChasakisD/Xamarin.Forms.BackgroundKit#36]
ava.lang.NoSuchMethodError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.getForeground()Landroid/graphics/drawable/Drawable;"
07-17 21:18:31.104 I/mono-stdout( 7091): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at android.os.Handler.handleCallback(Handler.java:739)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at android.os.Looper.loop(Looper.java:135)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-17 21:18:31.104 I/mono-stdout( 7091): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ChasakisD** [comment]
What is the API Version of the device? It cannot resolve Foreground property which was introduced in Android 6.0 (API 23).

**Comment by uksreejith** [comment]
Oh. This could be the reason. I was testing this on an Android 5.1 emulator(Memu Play). Let me test this on a later version of android.

**Comment by uksreejith** [comment]
Tested this on an emulator with android 7.1. It works fine.

**Comment by ChasakisD** [comment]
@uksreejith Glad you got it working! :)
