### ISSUE TITLE
Crash on android 4.4.2 Java.Lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by arappl-merc** [ChasakisD/Xamarin.Forms.BackgroundKit#53]
Greetings, 

Thank you for the great UI extensions.  I'm currently using a gradient as such:

`<bgkit:MaterialContentView Grid.Row="0" Grid.ColumnSpan="2" Background="{bgkit:BgProvider BorderWidth=4, GradientBrush={bgkit:LinearGradient Start=Blue, End=White, Angle=0}}"/>`

This works fine on iphones and several android devices but is crashing on an older HTC ONE M7 running android 4.4.2.

Crash information is as such:
> Java.Lang.IncompatibleClassChangeError: no method with name='getForeground' signature='()Landroid/graphics/drawable/Drawable;' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;
#### Full Stack trace:
<details>
  <summary>click to expand</summary> 
  
  > JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature)
> JniType.GetInstanceMethod (System.String name, System.String signature)
> JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember)
> JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
> View.get_Foreground ()
> MaterialBackgroundManager.UpdateRipple () /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:335
> MaterialBackgroundManager.UpdateBackground () /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:242
> MaterialBackgroundManager.SetBackgroundElement (XamarinBackgroundKit.Abstractions.IMaterialVisualElement oldElement, XamarinBackgroundKit.Abstractions.IMaterialVisualElement newElement) /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:148
> MaterialBackgroundManager.SetVisualElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:126
> /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:55
> MaterialContentViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialContentViewRenderer.cs:37
> VisualElementRenderer`1[TElement].SetElement (TElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:230
> IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
> VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
> VisualElementPackager.Load () D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
> VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:439
> VisualElementRenderer`1[TElement].SetElement (TElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:233
> IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
> VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
> VisualElementPackager.Load () D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
> VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:439
> VisualElementRenderer`1[TElement].SetElement (TElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:233
> IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> ScrollViewContainer.set_ChildView (Xamarin.Forms.View value) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewContainer.cs:37
> ScrollViewRenderer.LoadContent () D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:364
> ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:97
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
> VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
> VisualElementPackager.Load () D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
> VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:439
> VisualElementRenderer`1[TElement].SetElement (TElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:233
> IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
> VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
> VisualElementPackager.Load () D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
> VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:439
> VisualElementRenderer`1[TElement].SetElement (TElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:233
> IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127
> Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:345
> NavigationRenderer.SwitchContentAsync (Xamarin.Forms.Page view, System.Boolean animated, System.Boolean removed) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs:235
> NavigationRenderer.OnPushAsync (Xamarin.Forms.Page view, System.Boolean animated) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs:165
> NavigationRenderer.PushViewAsync (Xamarin.Forms.Page page, System.Boolean animated) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs:59
> NavigationRenderer.OnPushed (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs:202
> NavigationPage.PushAsyncInner (Xamarin.Forms.Page page, System.Boolean animated) D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:421
> NavigationPage.PushAsync (Xamarin.Forms.Page page, System.Boolean animated) D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:242
> BoatProfileListView.OnItemSelected (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs e) D:\Repo\VSTS\VVM1\VesselViewMobile.UI\Features\Profile\BoatProfileListView.xaml.cs:76
> AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
> SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
> Thread+RunnableImplementor.Run ()
> IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
> (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.29(intptr,intptr)
> java.lang.NoSuchMethodError: no method with name='getForeground' signature='()Landroid/graphics/drawable/Drawable;' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;
> md51558244f76c53b6aeda52c8a337f2c37.CellAdapter.n_onItemClick(Native Method)
> md51558244f76c53b6aeda52c8a337f2c37.CellAdapter.onItemClick CellAdapter.java:89
> android.widget.AdapterView.performItemClick AdapterView.java:299
> android.widget.AbsListView.performItemClick AbsListView.java:1282
> android.widget.ListView.performItemClick ListView.java:4450
> android.widget.AbsListView$PerformClick.run AbsListView.java:3174
> android.widget.AbsListView$3.run AbsListView.java:3925
> android.os.Handler.handleCallback Handler.java:733
> android.os.Handler.dispatchMessage Handler.java:95
> android.os.Looper.loop Looper.java:157
> android.app.ActivityThread.main ActivityThread.java:5872
> java.lang.reflect.Method.invokeNative(Native Method)
> java.lang.reflect.Method.invoke Method.java:515
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:858
> com.android.internal.os.ZygoteInit.main ZygoteInit.java:674
> dalvik.system.NativeStart.main(Native Method)
</details>

Any assistance would be greatly appreciated. I'd like to include gradients in my UI, but also can't isolate users with older android devices. 

Thanks,

Aaron

**Comment by ChasakisD** [comment]
Hey @arappl-merc,

First of all I would like to thank you for the feedback!

Tbh, I've never tested the library on Android OS below 5.1. Thanks for the stacktrace. This issue will be addressed and resolved soon!

**Comment by ChasakisD** [comment]
@arappl-merc are you using the latest stable version of the package? Try update to 2.0.0-beta and check if the crash happens.

**Comment by arappl-merc** [comment]
I was using 1.2.3. I now tried 2.0.0-beta. I still get the crash:
Java.Lang.IncompatibleClassChangeError
It appears like a slightly different crash maybe?
<details>
  <summary>crash details</summary>
  
  Java.Lang.IncompatibleClassChangeError
  Message=no method with name='setElevation' signature='(F)V' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;

</details>

**Comment by ChasakisD** [comment]
Now it makes sense. Will fix it soon. Thanks!

**Comment by bentmar** [comment]
I see the same on lollipop when im running your sample

**Comment by ChasakisD** [comment]
@bentmar @arappl-merc Version 2.0.0-beta2 published on nuget. I explained the problem with my sample in another [issue](https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/issues/54#issuecomment-559999939)
