### ISSUE TITLE
Not working on Android Lollipop

### ISSUE THREAD

**Issue by RobertHedgate** [ChasakisD/Xamarin.Forms.BackgroundKit#54]
Are using BackgroundKit in my app which is working great but it is crashing when using Android Lollipop phones. Getting error about getForeground.

Have debugged it and see that this line is crashing, on view.Foreground:
```c#
public static ShapeDrawable GetRippleMaskDrawable(this AView view)
{
    if (!(view.Foreground is RippleDrawable rippleDrawable)) return null;

    return rippleDrawable.GetDrawable(0) as ShapeDrawable;
}
```
If I fix it and return null I get a Scroll error which I don't really understand:
Java.Lang.ClassNotFoundException: 'mono.android.view.View_OnScrollChangeListenerImplementor'

Should Backgroundkit work on Android Lollipop?

**Comment by ChasakisD** [comment]
The actual reason for this Exception is from the Xamarin.Forms CollectionView implementation.
The RecyclerView.setOnScrollChangeListener() method was introduced in API 23 and in Xamarin.Forms implementation it is used without the check for the API Version. [ref](https://github.com/xamarin/Xamarin.Forms/blob/93effb986b8077417f6ace060613025f879072d6/Xamarin.Forms.Platform.Android/CollectionView/NongreedySnapHelper.cs#L22)

Although I improved the compatibility with versions above 19

Try version 2.0.0-beta2
