### ISSUE TITLE
Cannot change the Background of a MaterialContentView

### ISSUE THREAD

**Issue by toverux** [ChasakisD/Xamarin.Forms.BackgroundKit#63]
I came with the simplest code possible, basically:

```xaml
<bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=Blue}" x:Name="TestMaterialView">
    <Button Text="Change color to red" Clicked="OnButtonClicked" />
</bgKitControls:MaterialContentView>
```

```cs
private void OnButtonClicked(object sender, EventArgs e) {
    TestMaterialView.Background = new Background { Color = Color.Red };
}
```

Click the button and... nothing happens! Button stays blue.

It is a simple test case to demonstrate what I encounter in my app (can't change the elevation of a wrapped button).

I didn't test on iOS yet.

Repro on an empty app: [TestApp.zip](https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/files/4227971/TestApp.zip)

**Comment by ChasakisD** [comment]
Hey @toverux,

I will try the reproduction project and will investigate the issue. For now, do not change the whole background instance. Just change its color.

**Comment by toverux** [comment]
> For now, do not change the whole background instance. Just change its color.

Tested that (in my real app I'm changing Elevation though, Color is just an example), and that works, but the problem is, is that I use a `Style`. The `Background` is therefore shared between many views in the same page (eg. multiple buttons or form controls). If I change one, I change them all.

It looks like this:

```xaml
<Style x:Key="BaseControlMaterialView" TargetType="bgKitControls:MaterialContentView">
    <Setter Property="IsCornerRadiusHalfHeight" Value="True" />
    <Setter Property="Background" Value="{bgKitMarkup:BgProvider Color={StaticResource BrandWhite}, Elevation={StaticResource BaseElevation}}" />
    
    <Style.Triggers>
        <Trigger TargetType="bgKitControls:MaterialContentView" Property="IsEnabled" Value="False">
            <Setter Property="Background" Value="{bgKitMarkup:BgProvider Color={StaticResource BrandWhite}, Elevation=0}" />
        </Trigger>
    </Style.Triggers>
</Style>
```
Here, a view that gets `IsEnabled="False"` will take another background and the other views aren't touched, and I don't have to manage it by hand.

Edit : doesn't work better on iOS either!

Thanks for your help!

**Comment by ChasakisD** [comment]
Hello @toverux,

Thanks for your valuable feedback. 

Currently when setting a background via a style, all views share the same Background instance. This is because Background is mutable. Try setting a style for TargetType background and not for MaterialContentView.

Although setting a background via a style is pretty cool, I do not know how to fix this. If you have any ideas, I'm glad to discuss.

Atm, I am looking the issue above

**Comment by ChasakisD** [comment]
@toverux Version 2.0.5 just published on nuget. 

I'm gonna fill a new issue for the style issue
