### ISSUE TITLE
Unable to use Background in Style

### ISSUE THREAD

**Issue by ChasakisD** [ChasakisD/Xamarin.Forms.BackgroundKit#65]
> For now, do not change the whole background instance. Just change its color.

Tested that (in my real app I'm changing Elevation though, Color is just an example), and that works, but the problem is, is that I use a `Style`. The `Background` is therefore shared between many views in the same page (eg. multiple buttons or form controls). If I change one, I change them all.

It looks like this:

```xaml
<Style x:Key="BaseControlMaterialView" TargetType="bgKitControls:MaterialContentView">
    <Setter Property="IsCornerRadiusHalfHeight" Value="True" />
    <Setter Property="Background" Value="{bgKitMarkup:BgProvider Color={StaticResource BrandWhite}, Elevation={StaticResource BaseElevation}}" />
    
    <Style.Triggers>
        <Trigger TargetType="bgKitControls:MaterialContentView" Property="IsEnabled" Value="False">
            <Setter Property="Background" Value="{bgKitMarkup:BgProvider Color={StaticResource BrandWhite}, Elevation=0}" />
        </Trigger>
    </Style.Triggers>
</Style>
```
Here, a view that gets `IsEnabled="False"` will take another background and the other views aren't touched, and I don't have to manage it by hand.

Edit : doesn't work better on iOS either!

Thanks for your help!

_Originally posted by @toverux in https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/issues/63#issuecomment-588817783_

**Comment by ChasakisD** [comment]
@toverux

I am using the following xaml:
```xml
<ContentPage.Resources>
    <Style x:Key="BaseMaterialView" TargetType="controls:MaterialContentView">
        <Setter Property="Margin" Value="16" />
        <Setter Property="Padding" Value="16" />
        <Setter Property="HeightRequest" Value="60" />
        <Setter Property="IsCornerRadiusHalfHeight" Value="True" />
        <Setter Property="Background" Value="{controls:BgProvider Color=Green, Elevation=4}" />
        
        <Style.Triggers>
            <Trigger TargetType="controls:MaterialContentView" Property="IsEnabled" Value="False">
                <Setter Property="Background" Value="{controls:BgProvider Color=DarkGray, Elevation=0}" />
            </Trigger>
        </Style.Triggers>
    </Style>
</ContentPage.Resources>

<StackLayout BackgroundColor="White">
    <controls:MaterialContentView x:Name="TestView" Style="{StaticResource BaseMaterialView}" />
    
    <controls:MaterialContentView x:Name="TestView2" Style="{StaticResource BaseMaterialView}" />
    
    <Button Text="Test Me!" Clicked="OnTestMeClick"></Button>
</StackLayout>
```

and on xaml.cs
```cs
private void OnTestMeClick(object sender, EventArgs e)
{
    TestView.IsEnabled = !TestView.IsEnabled;
}
```

And I am unable to make a reproduction. Please test on 2.0.5 version

**Comment by toverux** [comment]
2.0.5 works just fine! In fact I don't think there was a problem with Style at all ;)
I may have confused you a bit with my story, but the real and only problem was the Backgroud property not reacting to reference changes.

Again, thank you again, that's hours of hard work saved.

**Comment by ChasakisD** [comment]
Alright then! Glad to hear that!

**Comment by ChasakisD** [comment]
Alright then! Glad to hear that!
