### ISSUE TITLE
Can't use transparent background colors

### ISSUE THREAD

**Issue by toverux** [ChasakisD/Xamarin.Forms.BackgroundKit#66]
Hi again,

I was trying to use a transparent background color, but it seems the alpha channel is lost on Android (I haven't tested on iOS yet).

But I've found that it's working flawlessly with gradients.

This is not working :

```xaml
{bgKitMarkup:BgProvider Color=Transparent}
```

While this works:

```xaml
{bgKitMarkup:BgProvider GradientBrush={bgKitMarkup:LinearGradient Start=Transparent, End=Transparent}}
```

**Comment by ChasakisD** [comment]
@toverux Version 2.0.7 published to nuget. It will be live soon.

**Comment by toverux** [comment]
Awesome, works fine.

Unrelated, but the release fixed another annoying issue I had with material views with IsCornerRadiusHalfHeight sometimes losing their radius for a short period of time, usually when changing pages (I also upgraded Xamarin.Forms so maybe it's that too).

Thank you very much!
