### ISSUE TITLE
Make BackgroundKit take ICommand and not concrete Xamarin.Forms.Command implementation

### ISSUE THREAD

**Issue by toverux** [ChasakisD/Xamarin.Forms.BackgroundKit#67]
Hello,

The library exposes a few command properties, I'll take the example of `MaterialContentView.ClickedCommand`.

This one holds a `Xamarin.Forms.Command` instance while typically it is recommended to use `System.Windows.Input.ICommand` instead. Even Xamarin.Forms uses it, see `Button.Command` for example.

I personally use ReactiveUI's `ReactiveCommand` to fulfill my needs. This implementation implements `ICommand` but does not inherit from `Xamarin.Forms.Command`, leading to this`kind of binding errors:

```
Binding: ReactiveUI.ReactiveCommand`2[Aterno.Binding.DisplayableRoom,System.Reactive.Unit] can not be converted to type 'Xamarin.Forms.Command'
````

Now I use a value converter to convert my commands on the fly:

```cs
public class ReactiveToXamarinCommandConverter : IValueConverter {
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) {
        var command = (ICommand) value;

        return new Command(param => command.Execute(param));
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) {
        throw new NotImplementedException();
    }
}
```

If you don't rely on this specific implementation of `ICommand`, could you use this base interface instead?

**Comment by ChasakisD** [comment]
Thank you for your feedback!

It's my mistake actually using Xamarin.Forms.Command instead of System.Windows.Input.ICommand. Gonna change it asap!

**Comment by ChasakisD** [comment]
@toverux Version 2.0.7 published to nuget. It will be live soon.

**Comment by toverux** [comment]
Works as expected!
