### ISSUE TITLE
About LinearGradient

### ISSUE THREAD

**Issue by samchenws** [ChasakisD/Xamarin.Forms.BackgroundKit#73]
Hello,How to use LinearGradient？
![image](https://user-images.githubusercontent.com/37535153/77982284-8bde7500-733e-11ea-8338-f7f42811fdb2.png)

**Comment by ChasakisD** [comment]
There are 2 ways for creating the Background of MaterialContentView. The one way is with the MarkupExtensions (the way you implemented it) and the other way is by opening the tag and create the Background. When using the first way, there are some cases where the X.F. linker links out BackgroundKit. To solve that, read below:

> Please confirm that your assembly contains a PackageReference to Xamarin.Forms Nuget Package. If not, add the Xamarin.Forms nuget package to that project. If this does not help, create a static class with a static constructor and just add the following
> 
> ```cs
> var x = typeof(MaterialContentView);
> ```
> 
> There are some cases where the xmlns is not working because there are no references in C# code.

**Comment by samchenws** [comment]
Thanks for you,ChasakisD.
