### ISSUE TITLE
 [Android] Two components in a stacklayout

### ISSUE THREAD

**Issue by moreirawebmaster** [ChasakisD/Xamarin.Forms.BackgroundKit#75]
When adding two components to a horizontal oriented stacklayout the first component applies the styles to the second.

Example: In the first component I put blue color, with shadow, and elevation, it happened that in the other that was on the side it was white color, elevation and shadow even though I entered values ​​like 0 in elevation, transparent shadow and color.

**Comment by toverux** [comment]
I am regularly observing the same behavior, and desperately trying to make a simple repro.
The thing is, it doesn't always happen. Worse, it seems not deterministic, ie. sometimes I open a page and it's fine, then I reopen it and the shadow copied the elevation value from... somewhere else.

A workaround that I found for the current occurence of the problem is to wrap the contaminated element in a ContentView. There it is isolated and applies the elevation I gave to it.

Also, no other values seem to be overriden, just the elevation.

**Comment by toverux** [comment]
Ah, here is a simple repro that seems to reliably fail. Each block has a different elevation value, 20, 10 and 0.

```xaml
<StackLayout Orientation="Horizontal">
    <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=20}" HorizontalOptions="FillAndExpand" HeightRequest="40" />
    <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=10}" HorizontalOptions="FillAndExpand" HeightRequest="40" />
    <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=0}" HorizontalOptions="FillAndExpand" HeightRequest="40" />
</StackLayout>
```

Renders:

![image](https://user-images.githubusercontent.com/1343250/79966152-4a4c7000-848d-11ea-888d-7a0fca38c4ba.png)

Not quite expected!

Now, let's reverse the elevation values in ascending order 0, 10, 20:

![image](https://user-images.githubusercontent.com/1343250/79966378-a3b49f00-848d-11ea-9f2b-6d80630a951f.png)

It's fine.

Now let's try 10, 0, 20:

![image](https://user-images.githubusercontent.com/1343250/79966553-e2e2f000-848d-11ea-9f8a-73a072ea9617.png)

This one's broken.

**It seems like elevation is applied from left to right, and that any subsequent element can't have an elevation lower than that of the previous one.**

Wrapping the material views in sub-views works well (10, 0, 20):

```xaml
<StackLayout Orientation="Horizontal" Spacing="10">
    <ContentView HorizontalOptions="FillAndExpand" HeightRequest="40">
        <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=10}" />
    </ContentView>
    <ContentView HorizontalOptions="FillAndExpand" HeightRequest="40">
        <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=0}" />
    </ContentView>
    <ContentView HorizontalOptions="FillAndExpand" HeightRequest="40">
        <bgKitControls:MaterialContentView Background="{bgKitMarkup:BgProvider Color=White, Elevation=20}" />
    </ContentView>
</StackLayout>
```

![image](https://user-images.githubusercontent.com/1343250/79966905-643a8280-848e-11ea-90e0-673c30ab3480.png)

Nesting material views works fine with different values (20, 10, 1):

![image](https://user-images.githubusercontent.com/1343250/79967496-33a71880-848f-11ea-9bd0-13c2f7d0a278.png)

Now, I have another strange behaviour in my app that I can't explain but maybe fixing this problem will help!

**Comment by ChasakisD** [comment]
Somehow, android applies elevation to the other views inside the same viewgroup. I was able to reproduce and fix the issue! By the end of the day, a new version will be available!
