### ISSUE TITLE
Object reference not set to an instance of an object  at XamarinBackgroundKit.iOS.Renderers.MaterialContentViewRenderer.TouchesEnded 

### ISSUE THREAD

**Issue by moreirawebmaster** [ChasakisD/Xamarin.Forms.BackgroundKit#76]
```{System.NullReferenceException: Object reference not set to an instance of an object  at XamarinBackgroundKit.iOS.Renderers.MaterialContentViewRenderer.TouchesEnded (Foundation.NSSet touches, UIKit.UIEvent evt) [0x00029] in /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.iOS/Renderers/MaterialContentViewRenderer.cs:99   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65   at Vitreo.App.iOS.Application.Main (System.String[] args) [0x00001] in C:\projects\Vitreo.App\Vitreo.App.iOS\Main.cs:17 }```

**Comment by ChasakisD** [comment]
@moreirawebmaster What version of BackgroundKit are you using?

**Comment by ChasakisD** [comment]
Closes due to inactivity

**Comment by moreirawebmaster** [comment]
> @moreirawebmaster What version of BackgroundKit are you using?

The last version man!
