### ISSUE TITLE
LinearGradientBrush could not found in namespace

### ISSUE THREAD

**Issue by sheharyarshahid** [ChasakisD/Xamarin.Forms.BackgroundKit#77]
Position 66:13. Type LinearGradient not found in xmlns http://xamarin.com/schemas/2014/forms/background

**Comment by ChasakisD** [comment]
Instead of using the url, try use the full namespace in xmlns. Could you please share X.F. and VS versions?

**Comment by sheharyarshahid** [comment]
X.F: **4.5.0.617**
VS: **Community 2019 16.6.5**

**Comment by sheharyarshahid** [comment]
I also tried using full namespace in xmlns. Still got the same error: **Type LinearGradient not found in 
xmlns clr-namespace:XamarinBackgroundKit.Controls;assembly=XamarinBackgroundKit**
Also cleaned the library project and build but it fails and shows the above error.

**Comment by sheharyarshahid** [comment]
**Background Resource**
`<background:Background
            x:Key="PrimaryGradientBrush"
            CornerRadius="8"
            GradientBrush="{background:LinearGradient Start={StaticResource TPrimaryColor},
                                                      End={StaticResource TSecondaryColor},
                                                      Angle=180}" />`

**Applied on Button**
`        <Button
            x:Name="ContinueBtn"
            Grid.Row="1"
            background:BackgroundEffect.Background="{StaticResource PrimaryGradientBrush}"
            Style="{StaticResource IntroContinueBtnStyle}" />`


I'm trying to create a background resource to be used as a background for the set of buttons. The first time I install the packages and created this resource it was working fine. The next time I worked on the project, it didn't let me build and run the app.

**Comment by toverux** [comment]
The LinearGradient you're trying to use in your last message is in the MarkupExtensions namespace, not Controls.

Use this :

```
xmlns:bgKitMarkup="clr-namespace:XamarinBackgroundKit.MarkupExtensions;assembly=XamarinBackgroundKit"
```

I also noticed that the auto import doesn't works with Rider/ReSharper, just on this library.
A bit annoying but not blocking, instead fix it by hand and copy/paste the imports the next times in other files.

**Comment by kylecode1690** [comment]
I am using:

**Comment by kylecode1690** [comment]
I am using: xmlns:controls="clr-namespace:XamarinBackgroundKit.Controls;assembly=XamarinBackgroundKit"

But is still getting background:GradientStop not found

**Comment by toverux** [comment]
First, you're aliasing the namespace as "controls" (`xmlns:controls`), not "background". And of course, change `XamarinBackgroundKit.Controls` to `XamarinBackgroundKit.MarkupExtensions` if GradientStop is effectively in `MarkupExtensions`.

**Comment by kylecode1690** [comment]
@toverux 
I have installed the background kit via the NuGet package. I have attached the code screenshot with the way i am setting the namespaces and error that is getting the output. I cant use the kit if this error is shown as I cant build and deploy.

![error](https://user-images.githubusercontent.com/38950845/88518072-c7850500-cfe7-11ea-945a-4c24e5b3d751.PNG)
![Capture](https://user-images.githubusercontent.com/38950845/88518075-c81d9b80-cfe7-11ea-9eb5-5975ec117764.PNG)

**Comment by ChasakisD** [comment]
@kylecode1690 replace the background url with the full namespace

**Comment by kylecode1690** [comment]
@ChasakisD What would this be? (Sorry i am new to Xamrain)

**Comment by ChasakisD** [comment]
Just remove the xmlns:background and in the gradientbrush replace background with controls

**Comment by kylecode1690** [comment]
@ChasakisD 

This worked for anyone having issues with the name spaces.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="CGRecycling.Views.Jobs.JobsForCollection"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:CGRecycling.ViewModels"
             xmlns:controls="clr-namespace:XamarinBackgroundKit.Controls;assembly=XamarinBackgroundKit"
             NavigationPage.HasNavigationBar="True"
             mc:Ignorable="d"
             Title="{Binding Title}"
             Style="{StaticResource ContentPageStyle}">`
