### ISSUE TITLE
Ripple not working if applied via a Style with an IsEnabled trigger

### ISSUE THREAD

**Issue by toverux** [ChasakisD/Xamarin.Forms.BackgroundKit#78]
So, this is a tough one, but I managed to narrow down the problem and make a simple repro.

Take this style:

```xaml
<Style TargetType="bgKitControls:MaterialContentView" x:Key="TestStyle">
    <Setter Property="IsClickable" Value="True" />
    <Setter Property="Background">
        <bgKitControls:Background Color="DodgerBlue" IsRippleEnabled="True" RippleColor="Magenta" />
    </Setter>

    <Style.Triggers>
        <Trigger TargetType="bgKitControls:MaterialContentView" Property="IsEnabled" Value="False">
            <Setter Property="Background" Value="{bgKitMarkup:BgProvider Color=Gray}" />
        </Trigger>
    </Style.Triggers>
</Style>
```

Apply it to this view:

```xaml
<bgKitControls:MaterialContentView
    Style="{StaticResource TestStyle}"
    WidthRequest="100" HeightRequest="40"
    IsEnabled="{Binding ShouldBeEnabled}">
</bgKitControls:MaterialContentView>
```

Now, the ripple is not working, when `IsEnabled=true`.

Remove the Trigger in the Style, or remove IsEnabled on the view (without touching the Style), and the ripple is showing up again.

**Also, IsEnabled must be a Binding**. It works if you pass `"True"` directly.

But... if the property that was bound in the Binding (ShouldBeEnabled in my example) was always true from the beginning, it works. However, if it goes from false to true at least once, there the ripple is broken.

I have this in my (ReactiveUI) ViewModel to demonstrate this non-deterministic effect:

```cs
public class Vm : ReactiveObject {
    [Reactive]
    public bool ShouldBeEnabled { get; set; } = false;

    public Vm(long roomId) {
        Device.StartTimer(TimeSpan.FromSeconds(2), () => {
            ShouldBeEnabled = true;
            return false;
        });
    }
}
```

If you replace `false` by true, no problem, it's working as intended.

**Comment by ChasakisD** [comment]
@toverux Thank you for your valuable feedback. The fix will be included in today's release!

**Comment by toverux** [comment]
Hi @ChasakisD, I hope you are well.
I'd still like to see this (and the other issues I created or participated in - mainly the adjacent shadows bug) fixed, however I didn't want to pressure you in any way in those difficult times, and given the help you already provided.
So, please take your time if you need it, I just wanted to show that I'm still here in case you need some motivation :)

Thanks again!

**Comment by ChasakisD** [comment]
@toverux Release 2.0.8 is published to nuget :)

**Comment by toverux** [comment]
That's working as intended (and for the other issues too).
Thank you so very much!
