### ISSUE TITLE
Border Gradient Brush doesn't work properly

### ISSUE THREAD

**Issue by freitas-patrick** [ChasakisD/Xamarin.Forms.BackgroundKit#80]
Gradient borders are being applied to the element's background, not the border itself. 
In this way, the background colors are completely ignored and the border remains white.

I tried to apply them to my project, and after failing, I did the download of the example project, and it behaved the same way.

![border_gradient](https://user-images.githubusercontent.com/26572725/82087866-55c73b80-96c7-11ea-9d86-0d9d450b4522.jpeg)

_In the downloaded and tested sample project, Xamarin forms is version 3.6.0.709228_

X.F: **4.6.0.726**
Visual Studio Community 2019 for Mac: 8.5.4
X.F.BackgroundKit: 2.0.7

**Comment by ChasakisD** [comment]
Thank you for your feedback!

Found the bug on GradientStrokeDrawable and will fix it soon!
