### ISSUE TITLE
2.0.8 - Not upgraded to use Xamarin.AndroidX for appcompat

### ISSUE THREAD

**Issue by MappingSteve** [ChasakisD/Xamarin.Forms.BackgroundKit#89]
Building with latest Xamarin.Forms which uses Xamarin.AndroidX for appcompat, get Build error:

    Can not resolve reference: 'Xamarin.Android.Support.Design', referenced by 'XamarinBackgroundKit.Android'.

Note the reference to an old Android.Support namespace, instead of to AndroidX.Support.

**Comment by tranb3r** [comment]
Seems like 2.1.0-beta1 has been migrated to AndroidX.
