### ISSUE TITLE
CornerRadius issue with MaterialContentView in CollectionView on Android

### ISSUE THREAD

**Issue by tranb3r** [ChasakisD/Xamarin.Forms.BackgroundKit#90]
The CornerRadius of MaterialContentView is not working properly when using it in a CollectionView.
The bug is only on Android. No issue on iOS.
Version 2.1.0-beta1 (androidx) with most recent version of xamarin forms.

Here is a sample repro project.
[repro.zip](https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/files/8179144/repro.zip)

Here is a screen record of both actual and expected behavior.
![actual2](https://user-images.githubusercontent.com/12516566/156601178-daab5506-924c-49fa-9762-c4eb300dcc23.gif)
![expected2](https://user-images.githubusercontent.com/12516566/156601177-79292527-4603-498a-b38c-e2edda670331.gif)

I think the issue is in `XamarinBackgroundKit.Android.PathProviders.RoundRectPathProvider`.
The `CanHandledByOutline` method uses `CornerRadii`, but it does not seem to hold the correct value when `IsPathDirty==true`.
https://github.com/ChasakisD/Xamarin.Forms.BackgroundKit/blob/4e7c51bcdaae90f738a0f220d520f97a8d49c69a/src/XamarinBackgroundKit.Android/PathProviders/RoundRectPathProvider.cs#L16

So here is a fix that works in my scenario.
Instead of:
```
public override bool CanHandledByOutline =>
      Math.Abs(CornerRadii.Sum() / CornerRadii.Length - CornerRadii[0]) < 0.0001;
```
check the value of IsPathDirty first:
```
public override bool CanHandledByOutline =>
      !IsPathDirty && Math.Abs(CornerRadii.Sum() / CornerRadii.Length - CornerRadii[0]) < 0.0001;
```

What do you think ?
Thanks !

**Comment by ChasakisD** [comment]
Impressive work! Thanks for the feedback! Please feel free to create a PR for this 🥳

**Comment by tranb3r** [comment]
Ok. I'll do the PR.
Before that, is there any reason not to merge the androidx branch into master ?

**Comment by ChasakisD** [comment]
Merged the androidx branch

**Comment by tranb3r** [comment]
I've prepared the PR.
By the way, are you planning to publish a stable nuget soon (ideally, including my fix) ?
Thanks again.

**Comment by ChasakisD** [comment]
@tranb3r Version 2.1.2 released to nuget. Thank you very much!
